// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwhvvQig9kJwDjfZ68S2MX4yM4OdNhAls',
    appId: '1:421874545936:web:44c907cb7d23f9456de195',
    messagingSenderId: '421874545936',
    projectId: 'mental-health-app-final',
    authDomain: 'mental-health-app-final.firebaseapp.com',
    storageBucket: 'mental-health-app-final.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB47QmRhq5d6pWFymL_e6D8Buh8ZISsAF0',
    appId: '1:421874545936:android:997080932f1337fd6de195',
    messagingSenderId: '421874545936',
    projectId: 'mental-health-app-final',
    storageBucket: 'mental-health-app-final.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIxyJ7l4atE1XtwZ7NatKTx65OAQahuX4',
    appId: '1:421874545936:ios:e7224191e42dadab6de195',
    messagingSenderId: '421874545936',
    projectId: 'mental-health-app-final',
    storageBucket: 'mental-health-app-final.firebasestorage.app',
    iosBundleId: 'com.example.mentalHealthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIxyJ7l4atE1XtwZ7NatKTx65OAQahuX4',
    appId: '1:421874545936:ios:e7224191e42dadab6de195',
    messagingSenderId: '421874545936',
    projectId: 'mental-health-app-final',
    storageBucket: 'mental-health-app-final.firebasestorage.app',
    iosBundleId: 'com.example.mentalHealthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwhvvQig9kJwDjfZ68S2MX4yM4OdNhAls',
    appId: '1:421874545936:web:564dba41fa1190be6de195',
    messagingSenderId: '421874545936',
    projectId: 'mental-health-app-final',
    authDomain: 'mental-health-app-final.firebaseapp.com',
    storageBucket: 'mental-health-app-final.firebasestorage.app',
  );
}
